name: Python & Rust docs

on:
  push:
    branches: [ develop ]

permissions:
  actions: read
  deployments: write
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/cleanup
      - uses: ./.github/actions/setup-rust
      - uses: spiraldb/actions/.github/actions/setup-uv@0.2.0

      - name: build Python and Rust docs
        run: |
          uv run make -C docs python-and-rust-html
      - name: commit python docs to gh-pages-bench
        run: |
          set -ex

          built_sha=$(git rev-parse HEAD)

          rm -rf docs/_build/html/rust/CACHETAG.DIR docs/_build/html/rust/debug

          mkdir /tmp/html
          mv docs/_build/html /tmp/html/docs

          mkdir -p /tmp/html/dev
          mv benchmarks-website /tmp/html/dev/bench
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: /tmp/html/
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
